// services/amend-watcher.mjs
//
// H4: Hermes amends a running continuable sub-agent mid-task.
//
// Protocol (file-based, no HTTP): Hermes writes
//   Hermes Home/inbox/dsh/amend/<ts>-<task_id>.json
//   { "task_id": "t-...", "content": [{ "type": "text", "text": "..." }], "ts": 123 }
// DSH polls the directory and, for each file whose task_id maps to a
// continuable child, delivers the content via ctx.subagents.followup() 鈥?the
// child's inbox is FIFO, so the amendment lands as the next turn (mid-run
// delivery queues until the current turn ends). Processed files are renamed
// into amend/done/; delivery failures leave the file in place and log.

import { readdirSync, readFileSync, existsSync, mkdirSync, renameSync } from 'node:fs'
import { join } from 'node:path'

const POLL_INTERVAL_MS = 2000

/**
 * v0.2.2 鈥?amend file naming convention:
 *   <ts>-<task_id>-<nonce>.json           (v0.2.2+, nonce required)
 *   <ts>-<task_id>.json                   (v0.2.0/v0.2.1 legacy 鈥?ignored)
 *
 * The nonce is generated by DSH at dispatch_task continuable time and is
 * returned in the metadata so Hermes can name its amend files uniquely.
 * DSH refuses to deliver any amend file whose nonce does not match the
 * registered entry for the given task_id. This closes the "any process
 * that can write to Hermes Home/inbox/dsh/amend/ can drive the running
 * sub-agent" attack surface present in v0.2.0/v0.2.1.
 */
function parseAmendFileName(name) {
  // Strip .json; tolerate v0.2.0/v0.2.1 two-segment names.
  const base = name.endsWith('.json') ? name.slice(0, -'.json'.length) : name
  const parts = base.split('-')
  // parts[0] = ts (numeric-ish), parts[1] = task_id, parts[2] = nonce (v0.2.2)
  if (parts.length < 3) return { legacy: true, ts: parts[0], task_id: parts.slice(1).join('-') || null }
  return { legacy: false, ts: parts[0], task_id: parts[1], nonce: parts.slice(2).join('-') }
}

/**
 * @param {object} deps
 * @param {string} deps.hermesHome
 * @param {object} deps.ctx            Cordis ctx (ctx.subagents, ctx.agents)
 * @param {object} deps.continuations  from services/continuations.mjs
 * @param {Function} deps.pickParentAgent
 * @returns {{ dispose: Function, deliver: Function, stats: Function }}
 */
export function createAmendWatcher({ hermesHome, ctx, continuations, pickParentAgent }) {
  const amendDir = join(hermesHome, 'inbox', 'dsh', 'amend')
  const doneDir  = join(amendDir, 'done')
  try { mkdirSync(amendDir, { recursive: true }) } catch {}
  try { mkdirSync(doneDir, { recursive: true }) } catch {}

  const stats = { delivered: 0, failed: 0, ignored: 0, scanned: 0, rejected_nonce: 0, rejected_legacy: 0 }
  // Files whose task_id is not (yet) registered are retried for a while, then
  // archived to done/ so they don't rescan forever.
  const UNKNOWN_RETRY_SCANS = 30 // 30 脳 2s 鈮?60s grace for registration
  const unknownSeen = new Map()

  /**
   * Deliver one amend request. Returns { status } 鈥?never throws.
   */
  async function deliver(filePath) {
    stats.scanned++
    const fileName = filePath.split(/[\\/]/).pop()

    // Parse the filename: nonce-segment is mandatory in v0.2.2+.
    const parsed = parseAmendFileName(fileName)
    if (parsed.legacy) {
      // Legacy two-segment name (v0.2.0/v0.2.1 protocol). Refuse 鈥?moving
      // aside so the file doesn't loop forever; NEVER deliver.
      stats.rejected_legacy++
      stats.ignored++
      try { renameSync(filePath, join(doneDir, `legacy-${Date.now()}-${fileName}`)) } catch {}
      return { status: 'rejected_legacy_format', file: fileName, note: 'v0.2.2+ requires a nonce segment in the filename; rename your Hermes amend writer to "<ts>-<task_id>-<nonce>.json". See docs/delivery-v0.6.0 "v0.2.2 hotfix".' }
    }

    let req
    try { req = JSON.parse(readFileSync(filePath, 'utf8')) } catch (e) {
      try { renameSync(filePath, join(doneDir, 'malformed-' + Date.now() + '.json')) } catch {}
      stats.ignored++
      return { status: 'malformed' }
    }

    if (!req || typeof req.task_id !== 'string' || !req.task_id) {
      stats.ignored++
      try { renameSync(filePath, join(doneDir, 'no-task-id-' + Date.now() + '.json')) } catch {}
      return { status: 'ignored_no_task_id' }
    }

    // Cross-check: filename task_id must equal body task_id (defense in
    // depth 鈥?the filename is the routing key; the body must agree).
    if (parsed.task_id !== req.task_id) {
      stats.ignored++
      try { renameSync(filePath, join(doneDir, `task-id-mismatch-${Date.now()}.json`)) } catch {}
      return { status: 'rejected_task_id_mismatch', file_task_id: parsed.task_id, body_task_id: req.task_id }
    }

    // CRITICAL: verify the filename nonce against the registered child.
    const validNonce = continuations.validateAmendNonce(req.task_id, parsed.nonce)
    if (!validNonce) {
      stats.rejected_nonce++
      stats.ignored++
      try { renameSync(filePath, join(doneDir, `bad-nonce-${Date.now()}-${fileName}`)) } catch {}
      return { status: 'rejected_nonce', task_id: req.task_id }
    }

    // Optional: trust on first use for entries that lack an amend_nonce
    // (legacy continuations rows created before the migration). We only
    // accept an empty amend_nonce if HERMES_LINK_TRUST_LEGACY=1 is set.
    const entry = continuations.getByTaskId(req.task_id)
    if (!entry) {
      const seen = (unknownSeen.get(filePath) || 0) + 1
      if (seen >= UNKNOWN_RETRY_SCANS) {
        unknownSeen.delete(filePath)
        stats.ignored++
        try { renameSync(filePath, join(doneDir, `ignored-${Date.now()}-${req.task_id}.json`)) } catch {}
        return { status: 'ignored_unknown_task', task_id: req.task_id }
      }
      unknownSeen.set(filePath, seen)
      return { status: 'retry_unknown_task', task_id: req.task_id }
    }
    unknownSeen.delete(filePath)

    const content = Array.isArray(req.content) && req.content.length > 0
      ? req.content
      : [{ type: 'text', text: String(req.text || req.amend || '') }]
    if (!content[0].text) {
      stats.ignored++
      try { renameSync(filePath, join(doneDir, `empty-${Date.now()}-${fileName}`)) } catch {}
      return { status: 'ignored_empty_content', task_id: req.task_id }
    }

    const parent = ctx.agents.get(entry.parent_agent_id) || pickParentAgent(ctx)
    if (!parent) {
      stats.failed++
      return { status: 'failed_no_parent', task_id: req.task_id }
    }
    try {
      const controller = new AbortController()
      const timer = setTimeout(() => controller.abort(new Error('amend deliver deadline')), 10_000)
      try {
        await ctx.subagents.followup(parent, entry.child_id, content, {
          signal: controller.signal,
          source: { kind: 'user' },
        })
      } finally {
        clearTimeout(timer)
      }
      try { renameSync(filePath, join(doneDir, `${Date.now()}-${fileName}`)) } catch {}
      // v0.3.0 F1 - SSE broker notification on successful amend delivery
      if (globalThis.__dsh_hermes_link_broker__) {
        try {
          globalThis.__dsh_hermes_link_broker__.publish(req.task_id, {
            kind: 'amend',
            data: { filename: fileName, content_preview: String(content[0].text || '').slice(0, 200) },
          })
        } catch (_e) {}
      }
      stats.delivered++
      return { status: 'delivered', task_id: req.task_id, child_id: entry.child_id }
    } catch (e) {
      stats.failed++
      return { status: 'failed_deliver', task_id: req.task_id, error: String(e && e.message || e) }
    }
  }

  let timer = null
  let stopped = false

  async function scanOnce() {
    if (stopped || !existsSync(amendDir)) return
    let files
    try { files = readdirSync(amendDir).filter((f) => f.endsWith('.json')) } catch { return }
    for (const f of files) {
      if (stopped) return
      const full = join(amendDir, f)
      try {
        await deliver(full)
      } catch (e) {
        console.warn('[dsh-hermes-link] amend deliver crashed:', e && e.message || e)
      }
    }
  }

  // Initial scan + interval.
  setTimeout(scanOnce, 3000)
  timer = setInterval(scanOnce, POLL_INTERVAL_MS)
  timer.unref?.()

  return {
    deliver,
    stats,
    dispose() {
      stopped = true
      if (timer) clearInterval(timer)
    },
  }
}